Config = Config or {}

--====================== Vehicles, Peds, Animal peds etc. ======================--

Config.randomHelicopters = {
    "maverick",
    "frogger",
    "frogger2",
    "supervolito",
    "supervolito2",
}

Config.randomBicycles = {
    "bmx",
    "tribike3",
    "scorcher",
    "cruiser",
    "tribike2",
    "tribike",
    "fixter",
    "inductor",
}

Config.randomCops = {  
    "s_f_y_cop_01",
    "s_m_y_cop_01",
    "csb_cop",
}

Config.randomPoliceVehicles = {
    "fbi",
    "police",
    "police2",
    "police3",
    "policet",
}

Config.randomMilitary = {
    "s_m_y_blackops_02",
    "s_m_y_blackops_01",
    "s_m_y_blackops_03",
    "s_m_y_armymech_01",
    "s_m_y_ammucity_01",
    "s_m_y_marine_03",
    "s_m_y_marine_01",
    "s_m_y_pilot_01",
}

Config.randomAirportVehicles = {
    "airtug",
    "airbus",
    "utillitruck3",
}

Config.randomPlanes = {
    "luxor",
    "mammatus",
    "miljet",
}

Config.randomAirportPeds = {
    "s_f_y_airhostess_01",
    "s_m_y_airworker",
    "s_m_y_construct_02",
    "s_m_y_construct_01",
}

Config.randomConstructionSitePeds = {
    "s_m_y_construct_02",
    "s_m_y_construct_01",
    "s_m_y_dockwork_01",
}

Config.randomBoats = {
    "dinghy",
    "dinghy2",
    "jetmax",
    "marquis",
    "seashark3",
    "tropic2",
    "toro",
    "tropic",
    "tug",
    "squalo",
    "toro2",
    "speeder",
    "speeder2",
    "suntrap",
    "seashark",
    "seashark2",
}

Config.randomTrainCarriages = {
    "freightcar",
    "freightcar2",
    "freightcont1",
    "freightcont2",
    "freightgrain",
}

Config.randomDirtObjects = {
    "prop_pile_dirt_07_cr",
    "prop_pile_dirt_07",
    "prop_pile_dirt_06",
    "prop_pile_dirt_04",
    "prop_pile_dirt_03",
    "prop_pile_dirt_02",
    "prop_pile_dirt_01",
}

Config.randomRiotObjects = {
    "prop_roadcone02a",
    "prop_ld_rubble_01",
    "prop_rock_4_a",
}

Config.randomRockObjects = {
    "prop_rock_4_a",
    "prop_rock_4_b",
    "prop_rock_4_c",
    "prop_rock_4_d",
    "prop_rock_4_e",
}

Config.RandomBombObjectModels = {
    "prop_ld_suitcase_02",
    "apa_mp_h_acc_box_trinket_01",
    "hei_prop_heist_box",
    "hei_prop_heist_ammo_box",
    "prop_cardbordbox_05a",
}

Config.allAnimals = { -- Birds/Fish are commented out, to prevent animal rescue not being able to reach animals which are alive but need rescuing.
    "a_c_boar",
    "a_c_cat_01",
    --"a_c_chickenhawk",
    "a_c_chimp",
    "a_c_chop",
    "a_c_cormorant",
    "a_c_cow",
    "a_c_coyote",
    --"a_c_crow",
    "a_c_deer",
    --"a_c_dolphin",
    --"a_c_fish",
    "a_c_hen",
    --"a_c_humpback",
    "a_c_husky",
    --"a_c_killerwhale",
    "a_c_mtlion",
    "a_c_pig",
    --"a_c_pigeon",
    "a_c_poodle",
    "a_c_pug",
    "a_c_rabbit_01",
    "a_c_rat",
    "a_c_retriever",
    "a_c_rhesus",
    "a_c_rottweiler",
    -- "a_c_seagull",
    --"a_c_sharkhammer",
    --"a_c_sharktiger",
    "a_c_shepherd",
    --"a_c_stingray",
    "a_c_westy",
}

Config.animalsBlockingRoads = { -- Specific animals for callouts (Realism, add or remove animals to your liking...)
    "a_c_boar",
    "a_c_cow",
    "a_c_deer",
    "a_c_mtlion",
    "a_c_pig",
}

Config.calloutAnimals = { -- Specific animals for callouts (Realism, add or remove animals to your liking...)
    "a_c_boar",
    "a_c_chimp",
    "a_c_cow",
    "a_c_deer",
    "a_c_mtlion",
    "a_c_pig",
}

Config.wildAnimals = {
    "a_c_mtlion",
}

Config.huntedAnimals = {
    "a_c_boar",
    "a_c_deer",
    "a_c_rabbit_01",
}

Config.cattleAnimals = { -- Specific animals for callouts (Realism, add or remove animals to your liking...)
    "a_c_cow",
    "a_c_pig",
}

Config.shopKeeperPeds = {
    "mp_m_shopkeep_01",
}

Config.randomGangPeds = {
        -- Gang female
        "g_f_importexport_01",
        "g_f_importexport_01",
        "g_f_y_ballas_01",
        "g_f_y_families_01",
        "g_f_y_lost_01",
        "g_f_y_vagos_01",
        -- Gang Male
        "g_m_importexport_01",
        "g_m_m_armboss_01",
        "g_m_m_armgoon_01",
        "g_m_m_armlieut_01",
        "g_m_m_chemwork_01",
        "g_m_m_chiboss_01",
        "g_m_m_chicold_01",
        "g_m_m_chigoon_01",
        "g_m_m_chigoon_02",
        "g_m_m_korboss_01",
        "g_m_m_mexboss_01",
        "g_m_m_mexboss_02",
        "g_m_y_armgoon_02",
        "g_m_y_azteca_01",
        "g_m_y_ballaeast_01",
        "g_m_y_ballaorig_01",
        "g_m_y_ballasout_01",
        "g_m_y_famca_01",
        "g_m_y_famdnf_01",
        "g_m_y_famfor_01",
        "g_m_y_korean_01",
        "g_m_y_korean_02",
        "g_m_y_korlieut_01",
        "g_m_y_lost_01",
        "g_m_y_lost_02",
        "g_m_y_lost_03",
        "g_m_y_mexgang_01",
        "g_m_y_mexgoon_01",
        "g_m_y_mexgoon_02",
        "g_m_y_mexgoon_03",
        "g_m_y_pologoon_01",
        "g_m_y_pologoon_02",
        "g_m_y_salvaboss_01",
        "g_m_y_salvagoon_01",
        "g_m_y_salvagoon_02",
        "g_m_y_salvagoon_03",
        "g_m_y_strpunk_01",
        "g_m_y_strpunk_02",
        "g_m_m_casrn_01",
}

Config.randomHunterPeds = {
    "cs_hunter",
    "mp_f_chbar_01",
    "csb_cletus",
    "a_f_m_eastsa_01"
}

Config.randomPeds = {
    -- Ambient female
    "a_f_m_beach_01",
    "a_f_m_bevhills_01",
    "a_f_m_bevhills_02",
    "a_f_m_bodybuild_01",
    "a_f_m_business_02",
    "a_f_m_downtown_01",
    "a_f_m_eastsa_01",
    "a_f_m_eastsa_02",
    "a_f_m_fatbla_01",
    "a_f_m_fatcult_01",
    "a_f_m_fatwhite_01",
    "a_f_m_ktown_01",
    "a_f_m_ktown_02",
    "a_f_m_prolhost_01",
    "a_f_m_salton_01",
    "a_f_m_skidrow_01",
    "a_f_m_soucent_01",
    "a_f_m_soucent_02",
    "a_f_m_soucentmc_01",
    "a_f_m_tourist_01",
    "a_f_m_tramp_01",
    "a_f_m_trampbeac_01",
    "a_f_o_genstreet_01",
    "a_f_o_indian_01",
    "a_f_o_ktown_01",
    "a_f_o_salton_01",
    "a_f_o_soucent_01",
    "a_f_o_soucent_02",
    "a_f_y_beach_01",
    "a_f_y_bevhills_01",
    "a_f_y_bevhills_02",
    "a_f_y_bevhills_03",
    "a_f_y_bevhills_04",
    "a_f_y_business_01",
    "a_f_y_business_02",
    "a_f_y_business_03",
    "a_f_y_business_04",
    "a_f_y_clubcust_01",
    "a_f_y_clubcust_02",
    "a_f_y_clubcust_03",
    "a_f_y_eastsa_01",
    "a_f_y_eastsa_02",
    "a_f_y_eastsa_03",
    "a_f_y_epsilon_01",
    "a_f_y_femaleagent",
    "a_f_y_fitness_01",
    "a_f_y_fitness_02",
    "a_f_y_genhot_01",
    "a_f_y_golfer_01",
    "a_f_y_hiker_01",
    "a_f_y_hippie_01",
    "a_f_y_hipster_01",
    "a_f_y_hipster_02",
    "a_f_y_hipster_03",
    "a_f_y_hipster_04",
    "a_f_y_indian_01",
    "a_f_y_juggalo_01",
    "a_f_y_runner_01",
    "a_f_y_rurmeth_01",
    "a_f_y_scdressy_01",
    "a_f_y_skater_01",
    "a_f_y_soucent_01",
    "a_f_y_soucent_02",
    "a_f_y_soucent_03",
    "a_f_y_tennis_01",
    "a_f_y_topless_01",
    "a_f_y_tourist_01",
    "a_f_y_tourist_02",
    "a_f_y_vinewood_01",
    "a_f_y_vinewood_02",
    "a_f_y_vinewood_03",
    "a_f_y_vinewood_04",
    "a_f_y_yoga_01",
    "a_f_y_gencaspat_01",
    "a_f_y_smartcaspat_01",
    -- Ambient male
    "a_m_m_acult_01",
    "a_m_m_afriamer_01",
    "a_m_m_beach_01",
    "a_m_m_beach_02",
    "a_m_m_bevhills_01",
    "a_m_m_bevhills_02",
    "a_m_m_business_01",
    "a_m_m_eastsa_01",
    "a_m_m_eastsa_02",
    "a_m_m_farmer_01",
    "a_m_m_fatlatin_01",
    "a_m_m_genfat_01",
    "a_m_m_genfat_02",
    "a_m_m_golfer_01",
    "a_m_m_hasjew_01",
    "a_m_m_hillbilly_01",
    "a_m_m_hillbilly_02",
    "a_m_m_indian_01",
    "a_m_m_ktown_01",
    "a_m_m_malibu_01",
    "a_m_m_mexcntry_01",
    "a_m_m_mexlabor_01",
    "a_m_m_og_boss_01",
    "a_m_m_paparazzi_01",
    "a_m_m_polynesian_01",
    "a_m_m_prolhost_01",
    "a_m_m_rurmeth_01",
    "a_m_m_salton_01",
    "a_m_m_salton_02",
    "a_m_m_salton_03",
    "a_m_m_salton_04",
    "a_m_m_skater_01",
    "a_m_m_skidrow_01",
    "a_m_m_socenlat_01",
    "a_m_m_soucent_01",
    "a_m_m_soucent_02",
    "a_m_m_soucent_03",
    "a_m_m_soucent_04",
    "a_m_m_stlat_02",
    "a_m_m_tennis_01",
    "a_m_m_tourist_01",
    "a_m_m_tramp_01",
    "a_m_m_trampbeac_01",
    "a_m_m_tranvest_01",
    "a_m_m_tranvest_02",
    "a_m_o_acult_01",
    "a_m_o_acult_02",
    "a_m_o_beach_01",
    "a_m_o_genstreet_01",
    "a_m_o_ktown_01",
    "a_m_o_salton_01",
    "a_m_o_soucent_01",
    "a_m_o_soucent_02",
    "a_m_o_soucent_03",
    "a_m_o_tramp_01",
    "a_m_y_acult_01",
    "a_m_y_acult_02",
    "a_m_y_beach_01",
    "a_m_y_beach_02",
    "a_m_y_beach_03",
    "a_m_y_beachvesp_01",
    "a_m_y_beachvesp_02",
    "a_m_y_bevhills_01",
    "a_m_y_bevhills_02",
    "a_m_y_breakdance_01",
    "a_m_y_busicas_01",
    "a_m_y_business_01",
    "a_m_y_business_02",
    "a_m_y_business_03",
    "a_m_y_clubcust_01",
    "a_m_y_clubcust_02",
    "a_m_y_clubcust_03",
    "a_m_y_cyclist_01",
    "a_m_y_dhill_01",
    "a_m_y_downtown_01",
    "a_m_y_eastsa_01",
    "a_m_y_eastsa_02",
    "a_m_y_epsilon_01",
    "a_m_y_epsilon_02",
    "a_m_y_gay_01",
    "a_m_y_gay_02",
    "a_m_y_genstreet_01",
    "a_m_y_genstreet_02",
    "a_m_y_golfer_01",
    "a_m_y_hasjew_01",
    "a_m_y_hiker_01",
    "a_m_y_hippy_01",
    "a_m_y_hipster_01",
    "a_m_y_hipster_02",
    "a_m_y_hipster_03",
    "a_m_y_indian_01",
    "a_m_y_jetski_01",
    "a_m_y_juggalo_01",
    "a_m_y_ktown_01",
    "a_m_y_ktown_02",
    "a_m_y_latino_01",
    "a_m_y_methhead_01",
    "a_m_y_mexthug_01",
    "a_m_y_motox_01",
    "a_m_y_motox_02",
    "a_m_y_musclbeac_01",
    "a_m_y_musclbeac_02",
    "a_m_y_polynesian_01",
    "a_m_y_roadcyc_01",
    "a_m_y_runner_01",
    "a_m_y_runner_02",
    "a_m_y_salton_01",
    "a_m_y_skater_01",
    "a_m_y_skater_02",
    "a_m_y_soucent_01",
    "a_m_y_soucent_02",
    "a_m_y_soucent_03",
    "a_m_y_soucent_04",
    "a_m_y_stbla_01",
    "a_m_y_stbla_02",
    "a_m_y_stlat_01",
    "a_m_y_stwhi_01",
    "a_m_y_stwhi_02",
    "a_m_y_sunbathe_01",
    "a_m_y_surfer_01",
    "a_m_y_vindouche_01",
    "a_m_y_vinewood_01",
    "a_m_y_vinewood_02",
    "a_m_y_vinewood_03",
    "a_m_y_vinewood_04",
    "a_m_y_yoga_01",
    "a_m_m_mlcrisis_01",
    "a_m_y_gencaspat_01",
    "a_m_y_smartcaspat_01",
    -- Gang female
    "g_f_importexport_01",
    "g_f_importexport_01",
    "g_f_y_ballas_01",
    "g_f_y_families_01",
    "g_f_y_lost_01",
    "g_f_y_vagos_01",
    -- Gang Male
    "g_m_importexport_01",
    "g_m_m_armboss_01",
    "g_m_m_armgoon_01",
    "g_m_m_armlieut_01",
    "g_m_m_chemwork_01",
    "g_m_m_chiboss_01",
    "g_m_m_chicold_01",
    "g_m_m_chigoon_01",
    "g_m_m_chigoon_02",
    "g_m_m_korboss_01",
    "g_m_m_mexboss_01",
    "g_m_m_mexboss_02",
    "g_m_y_armgoon_02",
    "g_m_y_azteca_01",
    "g_m_y_ballaeast_01",
    "g_m_y_ballaorig_01",
    "g_m_y_ballasout_01",
    "g_m_y_famca_01",
    "g_m_y_famdnf_01",
    "g_m_y_famfor_01",
    "g_m_y_korean_01",
    "g_m_y_korean_02",
    "g_m_y_korlieut_01",
    "g_m_y_lost_01",
    "g_m_y_lost_02",
    "g_m_y_lost_03",
    "g_m_y_mexgang_01",
    "g_m_y_mexgoon_01",
    "g_m_y_mexgoon_02",
    "g_m_y_mexgoon_03",
    "g_m_y_pologoon_01",
    "g_m_y_pologoon_02",
    "g_m_y_salvaboss_01",
    "g_m_y_salvagoon_01",
    "g_m_y_salvagoon_02",
    "g_m_y_salvagoon_03",
    "g_m_y_strpunk_01",
    "g_m_y_strpunk_02",
    "g_m_m_casrn_01",
    -- Tow driver
    "mp_m_waremech_01",
}

Config.randomMigrantVans = {
    "benson",
    "pounder",
    "pounder2",
    "granger",
    "burrito",
}

Config.randomMotorBikes = {
    "ruffian",     -- Motorbike
    "sanchez",     -- Motorbike
    "akuma",       -- Motorbike
    "bati",        -- Motorbike
    "faggio",      -- Moped
    "faggio2",     -- Moped
}

Config.randomFourDoorVehiclesSpecific = {
    "gburrito",
    "washington",
    "asterope",
    "schafter3",
    "schafter4",
    "schafter5",
    "tailgater",
    "jackal",
    "fugitive",
}

Config.randomHeavyVehicles = {
    "trash",
    "trash2",
    "tiptruck",
    "tiptruck2",
    "scrap",
}

Config.randomHeavyVehicles2 = {
    "bulldozer",
    "cutter",
    "dump",
    "handler"
}

Config.randomRiotVehicles = {
    "policet",
    "Sentinel",
    "FQ2",
    "baller3",
    "glendale",
    "asea",
    "asterope",
}

Config.RandomHeavyVehicleObjects = {
    "hei_prop_heist_binbag",
    "prop_ld_rub_binbag_01",
    "p_binbag_01_s",
    "prop_rub_binbag_01b",
    "prop_rub_binbag_sd_02",
    "prop_rub_binbag_03",
    "prop_rub_binbag_06",
    "prop_rub_binbag_08",
    "prop_rub_cardpile_05",
    "prop_rub_cardpile_06",
    "prop_rub_cardpile_07",
}

Config.RandomBagObjects = {
    "prop_beachbag_01",
    "prop_beachbag_02",
    "prop_beachbag_03",
    "prop_beachbag_04",
    "prop_beachbag_05",
    "prop_beachbag_06",
    "prop_ld_suitcase_02",
    "prop_suitcase_01",
    "prop_suitcase_01b",
    "prop_suitcase_01c",
    "prop_suitcase_02",
    "prop_suitcase_03",
    "prop_suitcase_03b",
}

Config.randomBuses = {
    "airbus",
    "tourbus",
    "bus",
    "rentalbus",
}

Config.randomVans = {
    "burrito",
    "burrito2",
    "burrito3",
    "burrito4",
    "gburrito",
    "gburrito2",
    "journey",
    "minivan",
    "minivan2",
    "paradise",
    "pony",
    "pony2",
    "rumpo",
    "rumpo2",
    "rumpo3",
    "speedo",
    "speedo2",
    "speedo4",
    "surfer",
    "surfer2",
    "taco",
    "youga",
    "youga2",
}

Config.randomPrisonerPeds = {
    "u_m_y_prisoner_01",
    "s_m_y_prismuscl_01",
    "s_m_y_prisoner_01",
}

Config.randomWasteDumpObjects = {
    "prop_rad_waste_barrel_01",
    "hei_prop_heist_binbag",
    "prop_ld_rub_binbag_01",
    "prop_oiltub_04",
    "prop_oilcan_02a",
    "prop_drug_bottle",
    "prop_drug_erlenmeyer",
}

Config.randomVehicles = { -- use vehicles with type 'automobile' only.
    "blista",
    "Issi2",
    "Sentinel",
    "FQ2",
    "baller3",
    "glendale",
    "asea",
    "asterope",
    "fugitive",
    "washington",
    "cognoscenti",
    "premier",
    "schafter2",
    "ingot",
    "turismor",
    "t20",
    "baller",
    "cavalcade",
    "granger",
    "huntley",
    "landstalker",
    "radi",
    "rocoto",
    "seminole",
    "xls",
    "bison",
    "bobcatxl",
    "gburrito",
    "journey",
    "minivan",
    "paradise",
    "rumpo",
    "surfer",
    "youga",
    "asea",
    "asterope",
    "cognoscenti",
    "cognoscenti2",
    "fugitive",
    "glendale",
    "ingot",
    "intruder",
    "premier",
    "primo",
    "primo2",
    "regina",
    "schafter2",
    "stanier",
    "stratum",
    "stretch",
    "superd",
    "surge",
    "tailgater",
    "warrener",
    "washington",
}

Config.randomDrugTrucks = {
    "pounder",
    "pounder2",
}

Config.randomTrucks = {
    "Benson",
    "Biff",
    "Hauler",
    "Hauler2",
    "Mule",
    "Mule2",
    "Mule3",
    "Packer",
    "Pounder",
    -- "Stockade",
    -- "Stockade3",
    "phantom",
    "phantom2",
}

Config.randomLuxuryVehicles = {
    "adder",
    "bullet",
    "cheetah",
    "entityxf",
    "fmj",
    "infernus",
    "italigtb",
    "italigtb2",
    "le7b",
    "osiris",
    "penetrator",
    "pfister811",
    "reaper",
    "sultanrs",
    "tempesta",
    "turismor",
    "tyrus",
    "vacca",
    "vagner",
    "zentorno",
}

Config.randomDrugObjects = {
    "prop_mp_drug_package",
    "prop_mp_drug_pack_red",
    "prop_mp_drug_pack_blue",
    "prop_drug_package_02",
    "hei_prop_hei_drug_case",
    "prop_cash_crate_01",
}

Config.randomCollissionObjects = {
    "prop_pile_dirt_01",
    "prop_log_break_01",
    "prop_rub_cardpile_06",
    "prop_rub_flotsam_01",
    "prop_rub_flotsam_02",
    "prop_rub_flotsam_03",
    "prop_tree_log_01",
    "prop_tree_log_02",
}

Config.randomDebris = {
    -- "prop_test_rocks02",
    -- "prop_test_rocks01",
    -- "prop_test_rocks04",
    "prop_rub_tyre_dam2",
    "prop_rub_tyre_dam3",
    "prop_cs_glass_scrap",
    "prop_rub_litter_01",
    "prop_rub_litter_02",
    "prop_rub_litter_03",
    "prop_rub_litter_03b",
    "prop_rub_litter_03c",
    "prop_rub_litter_04",
    "prop_rub_litter_04b",
    "prop_rub_litter_05",
    "prop_rub_litter_06",
    "prop_rub_litter_07",
    "prop_rub_litter_09",

}

Config.randomMoneyObjects = {
    "bkr_prop_bkr_cash_scatter_01",
    "bkr_cash_scatter_02",
    "prop_gold_bar",
    "bkr_prop_bkr_cashpile_04",
    "bkr_prop_bkr_cashpile_06",
    "ex_cash_pile_02",
    "ex_cash_pile_07",
    "ex_cash_pile_006",
    "prop_money_bag_01",
    "prop_security_case_01",
    "ex_cash_scatter_01",
    "prop_cash_case_02",
}

Config.randomDogs = {
    "a_c_shepherd",
    "a_c_rottweiler",
    "a_c_retriever",
    "a_c_husky",
    "a_c_poodle",
    "a_c_pug",
    "a_c_westy",
    "a_c_chop"
}



Config.parachuteObjects = {
    "p_para_broken1_s"
}

Config.randomMilitaryHelicopters = {
    "cargobob",
    "cargobob4",
}

Config.randomMoneyTransportPeds = {
    "s_m_m_armoured_01",
    "s_m_m_armoured_02",
}

Config.RandomNationalities = {
    "Afghan",
    "Albanian",
    "Algerian",
    "American",
    "Andorran",
    "Angolan",
    "Antiguans",
    "Argentinean",
    "Armenian",
    "Australian",
    "Austrian",
    "Azerbaijani",
    "Bahamian",
    "Bahraini",
    "Bangladeshi",
    "Barbadian",
    "Barbudans",
    "Batswana",
    "Belarusian",
    "Belgian",
    "Belizean",
    "Beninese",
    "Bhutanese",
    "Bolivian",
    "Bosnian",
    "Brazilian",
    "British",
    "Bruneian",
    "Bulgarian",
    "Burkinabe",
    "Burmese",
    "Burundian",
    "Cambodian",
    "Cameroonian",
    "Canadian",
    "Cape Verdean",
    "Central African",
    "Chadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Comoran",
    "Congolese",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Cypriot",
    "Czech",
    "Danish",
    "Djibouti",
    "Dominican",
    "Dutch",
    "East Timorese",
    "Ecuadorean",
    "Egyptian",
    "Emirian",
    "Equatorial Guinean",
    "Eritrean",
    "Estonian",
    "Ethiopian",
    "Fijian",
    "Filipino",
    "Finnish",
    "French",
    "Gabonese",
    "Gambian",
    "Georgian",
    "German",
    "Ghanaian",
    "Greek",
    "Grenadian",
    "Guatemalan",
    "Guinea-Bissauan",
    "Guinean",
    "Guyanese",
    "Haitian",
    "Herzegovinian",
    "Honduran",
    "Hungarian",
    "I-Kiribati",
    "Icelander",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Ivorian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kazakhstani",
    "Kenyan",
    "Kittian and Nevisian",
    "Kuwaiti",
    "Kyrgyz",
    "Laotian",
    "Latvian",
    "Lebanese",
    "Liberian",
    "Libyan",
    "Liechtensteiner",
    "Lithuanian",
    "Luxembourger",
    "Macedonian",
    "Malagasy",
    "Malawian",
    "Malaysian",
    "Maldivan",
    "Malian",
    "Maltese",
    "Marshallese",
    "Mauritanian",
    "Mauritian",
    "Mexican",
    "Micronesian",
    "Moldovan",
    "Monacan",
    "Mongolian",
    "Moroccan",
    "Mosotho",
    "Motswana",
    "Mozambican",
    "Namibian",
    "Nauruan",
    "Nepalese",
    "New Zealander",
    "Nicaraguan",
    "Nigerian",
    "Nigerien",
    "North Korean",
    "Northern Irish",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Palauan",
    "Panamanian",
    "Papua New Guinean",
    "Paraguayan",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Qatari",
    "Romanian",
    "Russian",
    "Rwandan",
    "Saint Lucian",
    "Salvadoran",
    "Samoan",
    "San Marinese",
    "Sao Tomean",
    "Saudi",
    "Scottish",
    "Senegalese",
    "Serbian",
    "Seychellois",
    "Sierra Leonean",
    "Singaporean",
    "Slovakian",
    "Slovenian",
    "Solomon Islander",
    "Somali",
    "South African",
    "South Korean",
    "Spanish",
    "Sri Lankan",
    "Sudanese",
    "Surinamer",
    "Swazi",
    "Swedish",
    "Swiss",
    "Syrian",
    "Taiwanese",
    "Tajik",
    "Tanzanian",
    "Thai",
    "Togolese",
    "Tongan",
    "Trinidadian or Tobagonian",
    "Tunisian",
    "Turkish",
    "Tuvaluan",
    "Ugandan",
    "Ukrainian",
    "Uruguayan",
    "Uzbekistani",
    "Venezuelan",
    "Vietnamese",
    "Welsh",
    "Yemenite",
    "Zambian",
    "Zimbabwean"
}
