Config = Config or {}

--====================== Vehicle Interactions Settings ======================--

Config.DisableTaxAndMOT = false -- Disables tax / MOT checks if you have a US server for example.

Config.VehicleBuildYearRange = {1990, 2024} -- Years
Config.VehicleTaxNotPaidChance = 15 -- Out of 100%
Config.VehicleMOTInvalidChance = 15
Config.VehicleInsuranceInvalidChance = 15
Config.VehicleStolenChance = 15
Config.VehicleBoloChance = 15
Config.BoloDescriptions = { -- Randomly selected from this list.
    "Vehiculo implicado en un atropello con fuga.",
"Vehiculo denunciado por conduccion temeraria.",
"Vehiculo denunciado por ser conducido bajo los efectos de sustancias.",
"Vehiculo denunciado por haber sido utilizado en un robo reciente.",
"Vehiculo denunciado por haber sido utilizado en un tiroteo reciente.",
"Vehiculo denunciado por haber sido utilizado en un secuestro reciente.",
"Vehiculo denunciado por haber sido utilizado recientemente para traficar con drogas.",
"Vehiculo denunciado por haber sido utilizado en un incendio provocado reciente.",
"Vehiculo denunciado por haber sido utilizado recientemente en un caso de trata de personas.",
}

Config.EnableVehicleSearch = true
Config.VehicleSearchChance = 15     -- Out of 100%
Config.VehicleSearchDuration = 5000 -- Milliseconds (5 sec default.)
Config.PropListOfPropsToFindInVehicle = {
    -- Illegal generic props
    { Name = "gun", Model = "w_sg_assaultshotgun_mag1", Illegal = true },
    { Name = "pack of drugs", Model = "ex_office_swag_drugbag2", Illegal = true },
    { Name = "bundle of cash", Model = "bkr_prop_bkr_cashpile_01", Illegal = true },
    { Name = "cash pile", Model = "prop_cash_pile_01", Illegal = true },
    { Name = "bundle of weed", Model = "bkr_prop_weed_bigbag_01a", Illegal = true },
    { Name = "open bundle of weed", Model = "bkr_prop_weed_bigbag_open_01a", Illegal = true },
    { Name = "bag of cash", Model = "hei_p_f_bag_var6_bus_s", Illegal = true },
    { Name = "knife", Model = "prop_knife_01", Illegal = true },
    { Name = "pistol", Model = "w_pi_pistol", Illegal = true },
    { Name = "baseball bat", Model = "w_me_bat", Illegal = true },
    { Name = "crowbar", Model = "w_me_crowbar", Illegal = true },
    { Name = "screwdriver", Model = "prop_tool_screwdvr01", Illegal = true },
    { Name = "bulletproof vest", Model = "prop_armour_pickup", Illegal = true },
    { Name = "stack of cocaine bricks", Model = "bkr_prop_coke_block_01a", Illegal = true },
    { Name = "meth tray", Model = "bkr_prop_meth_tray_02a", Illegal = true },
    { Name = "bag of counterfeit money", Model = "bkr_prop_fakeid_binbag_01", Illegal = true },
    { Name = "stolen piece of jewelry", Model = "p_jewel_necklace01_s", Illegal = true },

    -- Drug related props   
    { Name = "can of ammonia", Model = "bkr_prop_meth_ammonia", Illegal = true },
    { Name = "can of acetone", Model = "bkr_prop_meth_acetone", Illegal = true },
    { Name = "can of hydrochloric acid", Model = "bkr_prop_meth_hcacid", Illegal = true },
    { Name = "can of lithium", Model = "bkr_prop_meth_lithium", Illegal = true },
    { Name = "can of sulfuric acid", Model = "bkr_prop_meth_sacid", Illegal = true },
    { Name = "can of sodium", Model = "bkr_prop_meth_sodium", Illegal = true },
    { Name = "burger", Model = "prop_cs_burger_01", Illegal = false },       
    { Name = "baking soda", Model = "bkr_prop_coke_bakingsoda", Illegal = true },

    -- Food & drinks related props
    { Name = "sodacan", Model = "ng_proc_sodacan_02a", Illegal = false },
    { Name = "sodacup", Model = "ng_proc_sodacup_01c", Illegal = false },
    { Name = "sodacup", Model = "ng_proc_sodacup_03a", Illegal = false },
    { Name = "bottle of alcohol", Model = "apa_mp_h_acc_bottle_02", Illegal = false },
    { Name = "bottle of alcohol", Model = "apa_mp_h_acc_bottle_01", Illegal = false },
    { Name = "bottle of cognac", Model = "prop_bottle_cognac", Illegal = false },
    { Name = "bottle of brandy", Model = "prop_bottle_brandy", Illegal = false },
    { Name = "beer bottle", Model = "prop_beer_bottle", Illegal = false },
    { Name = "richard bottle", Model = "prop_bottle_richard", Illegal = false },
    { Name = "whiskey bottle", Model = "prop_cs_whiskey_bottle", Illegal = false },
    { Name = "set of body parts", Model = "v_ilev_body_parts", Illegal = false },
    { Name = "food bag", Model = "ng_proc_food_bag01a", Illegal = false },
    { Name = "food bag", Model = "ng_proc_food_bag02a", Illegal = false },
    { Name = "coffee cup", Model = "prop_food_bs_coffee", Illegal = false },
    { Name = "juice cup", Model = "prop_food_bs_juice02", Illegal = false },
    { Name = "food tray", Model = "prop_food_cb_tray_02", Illegal = false },

    -- Clothing related props
    { Name = "set of panties", Model = "prop_cs_panties", Illegal = false },
    { Name = "t-shirt", Model = "prop_ld_tshirt_02", Illegal = false },

    -- Other props (add yours here in the correct format)
    -- { Name = "item name", Model = "object_model", Illegal = false },
}

Config.VehicleBonesToSearch = {
    -- Driver front door - camera positioned to look through the door into the interior
    { Name = "front door", DoorBone = "door_dside_f", DoorIndex = 0, SeatBone = "seat_dside_f", SeatIndex = -1, SearchRadius = 3.0, 
      AnimationDictionary = "amb@code_human_police_investigate@idle_a", AnimationName = "idle_c", 
      CamSideOffest = -2.5, CamForwardOffset = 0.0, CamHeightOffset = 0.8, OffsetDistance = 0.75 },
    
    -- Passenger front door
    { Name = "front door", DoorBone = "door_pside_f", DoorIndex = 1, SeatBone = "seat_pside_f", SeatIndex = 0, SearchRadius = 3.0, 
      AnimationDictionary = "amb@code_human_police_investigate@idle_a", AnimationName = "idle_c", 
      CamSideOffest = 2.5, CamForwardOffset = 0.0, CamHeightOffset = 0.8, OffsetDistance = 0.75 },
    
    -- Driver rear door
    { Name = "rear door", DoorBone = "door_dside_r", DoorIndex = 2, SeatBone = "seat_dside_r", SeatIndex = 1, SearchRadius = 3.0, 
      AnimationDictionary = "amb@code_human_police_investigate@idle_a", AnimationName = "idle_c", 
      CamSideOffest = -2.5, CamForwardOffset = -1.2, CamHeightOffset = 0.8, OffsetDistance = 0.75 },
    
    -- Passenger rear door
    { Name = "rear door", DoorBone = "door_pside_r", DoorIndex = 3, SeatBone = "seat_pside_r", SeatIndex = 2, SearchRadius = 3.0, 
      AnimationDictionary = "amb@code_human_police_investigate@idle_a", AnimationName = "idle_c", 
      CamSideOffest = 2.5, CamForwardOffset = -1.2, CamHeightOffset = 0.8, OffsetDistance = 0.75 },
    
    -- Bonnet - closer overhead view
    { Name = "bonnet", DoorBone = "bonnet", DoorIndex = 4, SeatBone = nil, SeatIndex = nil, SearchRadius = 3.0, 
      AnimationDictionary = "mini@repair", AnimationName = "fixing_a_ped", 
      CamSideOffest = 0.0, CamForwardOffset = 3.5, CamHeightOffset = 1.8, OffsetDistance = 1.8 },
    
    -- Boot - closer overhead view
    { Name = "boot", DoorBone = "boot", DoorIndex = 5, SeatBone = nil, SeatIndex = nil, SearchRadius = 3.0, 
      AnimationDictionary = "mini@repair", AnimationName = "fixing_a_ped", 
      CamSideOffest = 0.0, CamForwardOffset = -3.5, CamHeightOffset = 1.8, OffsetDistance = 1.5 },
}

Config.BonePropOffsetData = { 
    -- This is used for prop positioning relative to the bones for seats, bonnet and boot. (We left it default, because most props are attached fine by default.)
    {bone = "seat_dside_f", relatedDoorBone = "door_dside_f", offsetX = 0.0, offsetY = 0.0, offsetZ = 0.0, rotationX = 0.0, rotationY = 0.0, rotationZ = 0.0},
    {bone = "seat_pside_f", relatedDoorBone = "door_pside_f", offsetX = 0.0, offsetY = 0.0, offsetZ = 0.0, rotationX = 0.0, rotationY = 0.0, rotationZ = 0.0},
    {bone = "seat_dside_r", relatedDoorBone = "door_dside_r", offsetX = 0.0, offsetY = 0.0, offsetZ = 0.0, rotationX = 0.0, rotationY = 0.0, rotationZ = 0.0},
    {bone = "seat_pside_r", relatedDoorBone = "door_pside_r", offsetX = 0.0, offsetY = 0.0, offsetZ = 0.0, rotationX = 0.0, rotationY = 0.0, rotationZ = 0.0},
    {bone = "bonnet", relatedDoorBone = "bonnet", offsetX = 0.0, offsetY = 0.0, offsetZ = 0.0, rotationX = 0.0, rotationY = 0.0, rotationZ = 0.0},
    {bone = "boot", relatedDoorBone = "boot", offsetX = 0.0, offsetY = 0.0, offsetZ = 0.0, rotationX = 0.0, rotationY = 0.0, rotationZ = 0.0},
}

Config.VehicleSearchMarkerData = {
    Type = 6,
    Offset = {x = 0.0, y = 0.0, z = 0.1},
    Direction = {x = 0.0, y = 0.0, z = 0.0},
    Rotation = {x = 0.0, y = 0.0, z = 0.0},
    Scale = {x = 0.15, y = 0.15, z = 0.15},
    Color = {r = 255, g = 193, b = 7, a = 155},
    BobUpAndDown = false,
    FaceCamera = true,
    P19 = false,
    Rotate = false,
    TextureDict = nil,
    TextureName = nil,
    DrawOnEnts = false
}

Config.VehicleColours = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Util Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "hunter green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foliage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Pure Gold",
    [159] = "Brushed Gold",
    [160] = "MP100_GOLD"
}
