-- Las siguientes tablas definen qué preguntas hará el agente ("OFC"), qué órdenes dará y qué información comunicará.
-- También se definen las respuestas del peatón ("Normal").
NormalAddress = {'Hola, agente.', '¿En qué puedo ayudarle?'}
NormalGreetResponse = NormalAddress
NormalLicenceResponse = {'Claro, aquí tiene.', 'Por supuesto, agente.'}
NormalLicenceHideResponse = {"Eh, ahora mismo no lo encuentro...", "Mmm... tiene que estar por aquí.", "Lo siento, agente, parece que lo he perdido."}
NormalNoLicenceResponse = {"No tengo ninguno, agente.", "No tengo, lo siento."}
NormalNoDrugResponse = {"No, no consumo drogas.", "No, agente, eso sería ilegal.", "Por supuesto que no."}
NormalDrugResponse = {"¿D-d-drogas? N-no.", "Cuántos colores..."}
NormalNoAlcoholResponse = {"No, no he bebido nada.", "No, agente."}
NormalAlcoholHideResponse = NormalNoAlcoholResponse
NormalAlcoholResponse = {"Sí, he bebido un poco, pero no ha sido mucho.", "Puede que me haya tomado un par de copas...", "Sí, pero eso no es ilegal, agente."}
NormalNoIllegalItemsResponse = {"No, agente.", "Por supuesto que no.", "No llevo nada ilegal."}
NormalIllegalItemsResponse = {"Bueno, en realidad encontré esto hace unos minutos...", "¿Objetos ilegales? Nooo..."}
NormalIllegalItemsHideResponse = NormalNoIllegalItemsResponse
NormalNoWeaponsResponse = {"Voy desarmado.", "No, agente.", "No llevo ningún arma."}
NormalWeaponsResponse = {"Sí, llevo un arma conmigo.", "Voy armado.", "Sí, agente.", "Sí, encontré esta arma...", "Sí, pero está todo en regla."}
NormalWeaponsHideResponse = NormalNoWeaponsResponse
NormalIllegalWeaponsResponse = NormalWeaponsResponse
NormalIllegalWeaponsHideResponse = NormalNoWeaponsResponse
NormalAnswerStartingPoint = {"Salí de casa.", "Vengo del trabajo.", "Vengo del club de striptease.", "Acabo de salir del banco.", "Estaba comprando comida.", "De ningún sitio en particular.", "Vengo de la prisión.", "Vengo de la comisaría.", "Estaba en casa."}
NormalAnswerDestination = {"Voy a casa.", "Voy de camino al trabajo.", "Voy a por una pizza.", "A ningún sitio en especial.", "Voy al club de striptease.", "Tengo que comprar comida.", "Voy al banco.", "Voy a la comisaría."}
NormalAnswerActivity = {"¡Estoy caminando!", "Solo estoy caminando.", "Estoy aquí sin hacer nada.", "Solo estoy dando una vuelta sin rumbo.", "La verdad, no lo sé muy bien..."}
NormalAnswerNoSuspiciousActivity = {"No he visto nada.", "No, agente, nada sospechoso.", "Nada fuera de lo normal."}
NormalNoVehicleResponse = {"Agente, aquí no hay ningún vehículo.", "Agente, no tengo ningún vehículo.", "¿Qué vehículo?", "Agente, ¿está de broma? Aquí no hay ningún vehículo..."}
NormalAcceptOrderResponse = {"Sí, agente.", "De acuerdo, agente.", "Entendido.", "Adelante."}
NormalRefuseOrderResponse = {"No, agente.", "No.", "Eso no va a pasar, agente.", "Me niego."}
NormalRefuseQuestionResponse = {"No necesita saber eso.", "No hay ningún motivo para que tenga esa información.", "Agente, me niego a responder.", "Me niego a responder.", "No voy a darle esa información."}
NormalResistActionResponse = {"¡No me toque!", "¡No puede hacer esto!", "¡Deje de tocarme!", "¡Aléjese!"}
NormalStopInteractionResponse = {"Agente, no voy a seguir hablando con usted. Adiós."}
NormalFleeResponse = {"¡No me siga, agente!"}
NormalFightResponse = {"¡Va a pagar por esto!"}
NormalWaitResponse = {'Por favor, dese prisa.', "De acuerdo, esperaré.", 'De acuerdo, agente.'}
NormalGoodbye = {'Hasta pronto.', 'Adiós.', 'Hasta luego.', 'Buen día, agente.', 'Que tenga un buen día.'}

OFCAskForID = {'¿Puede mostrarme su identificación?', 'Entrégueme su identificación.', 'Identificación, por favor.', '¿Lleva algún documento de identidad?'}
OFCAskForDriverLicence = {"¿Puede mostrarme su permiso de conducir?", "Permiso de conducir, por favor.", "Entrégueme su permiso de conducir.", "¿Tiene permiso de conducir?"}
OFCAskForGunLicence = {"¿Puede mostrarme su licencia de armas?", "Entrégueme su licencia de armas.", "Licencia de armas, por favor.", "¿Tiene licencia de armas?"}
OFCAskForSubstance = {"¿Ha consumido alguna sustancia controlada?", "¿Consume drogas?"}
OFCAskForAlcohol = {"¿Ha estado bebiendo?", "¿Ha bebido alcohol hoy?", "¿Está bajo los efectos del alcohol?"}
OFCAskForIllegalItems = {"¿Lleva algo ilegal encima?", "¿Lleva algo que no debería llevar?"}
OFCAskForWeapons = {"¿Lleva algún arma de fuego?", "¿Va armado?", "¿Lleva armas encima?"}
OFCAskForStartingPoint = {"¿De dónde viene?"}
OFCAskForDestination = {"¿Adónde se dirige?"}
OFCAskForActivity = {"¿Qué está haciendo en este momento?"}
OFCAskForSuspiciousActivity = {"¿Ha visto algo sospechoso últimamente?"}
OFCOrderOutOfVehicle = {"Por favor, salga del vehículo.", "¡Salga del vehículo inmediatamente!", "Salga del vehículo."}
OFCOrderIntoVehicle = {"Por favor, entre en el vehículo.", "¡Entre en el vehículo inmediatamente!", "Vuelva a entrar en el vehículo."}
OFCInformBreathalyzer = {"Por favor, sométase a la prueba de alcoholemia.", "Voy a comprobar su nivel de alcohol.", "Por favor, sople en el alcoholímetro."}
OFCInformDrugtest = {"Por favor, sométase a una prueba de drogas.", "Voy a realizarle una prueba para detectar sustancias ilegales."}
OFCInformPersonSearch = {"Por favor, permita que le registre.", "Voy a registrarle. ¿Lleva algo en los bolsillos que pueda hacerme daño?", "Voy a proceder a registrarle."}
OFCInformCarSearch = {"Voy a registrar su vehículo.", "Por favor, permita el registro del vehículo."}
OFCInformCarSeizure = {"Tengo que decomisar su vehículo.", "No puede seguir conduciendo este vehículo.", "Su vehículo será decomisado."}
OFCInformObjectConfiscation = {"Tengo que retirarle estos objetos.", "Voy a confiscarle estos objetos."}
OFCInformArrest = {"Queda usted detenido.", "Por favor, dese la vuelta. Queda usted detenido."}
OFCInformFine = {"Voy a imponerle una multa.", "Tengo que extenderle una sanción."}

OFCWait = {"Espere aquí, volveré enseguida.", "Por favor, espere aquí.", "Permanezca en la zona mientras realizo unas comprobaciones."}
OFCBye = {'Que tenga un buen día.', 'De acuerdo, puede marcharse.', 'Adiós.', 'Puede retirarse.', 'Hasta luego.'}
