Config = {}

-- Cada entrada admite valores distintos para mp_m_freemode_01 y mp_f_freemode_01.
-- `collection` es opcional: úsalo sólo para props de una collection EUP conocida.
-- No se muestran props que no estén listados aquí.
Config.Accessories = {
    police = {
        glasses = {
            { label = 'Gafas tácticas', male = { drawable = 23, texture = 0 }, female = { drawable = 25, texture = 0 } },
            { label = 'Gafas profesionales oscuras', male = { drawable = 5, texture = 1 }, female = { drawable = 11, texture = 0 } },
            { label = 'Gafas profesionales claras', male = { drawable = 5, texture = 2 }, female = { drawable = 11, texture = 5 } },
            { label = 'Gafas EMS 63-0', male = { drawable = 63, texture = 0 }, female = { drawable = 63, texture = 0 } },
            { label = 'Gafas EMS 1-1', male = { drawable = 1, texture = 1 }, female = { drawable = 1, texture = 1 } },
            { label = 'Gafas EMS 2-2', male = { drawable = 2, texture = 2 }, female = { drawable = 2, texture = 2 } },
            { label = 'Gafas EMS 3-9', male = { drawable = 3, texture = 9 }, female = { drawable = 3, texture = 9 } },
            { label = 'Gafas EMS 4-6', male = { drawable = 4, texture = 6 }, female = { drawable = 4, texture = 6 } },
            { label = 'Gafas EMS 7-7', male = { drawable = 7, texture = 7 }, female = { drawable = 7, texture = 7 } },
            { label = 'Gafas EMS 9-9', male = { drawable = 9, texture = 9 }, female = { drawable = 9, texture = 9 } },
            { label = 'Gafas EMS 15-7', male = { drawable = 15, texture = 7 }, female = { drawable = 15, texture = 7 } },
            { label = 'Gafas EMS 17-7', male = { drawable = 17, texture = 7 }, female = { drawable = 17, texture = 7 } },
            { label = 'Gafas EMS 17-9', male = { drawable = 17, texture = 9 }, female = { drawable = 17, texture = 9 } },
            { label = 'Gafas EMS 19-9', male = { drawable = 19, texture = 9 }, female = { drawable = 19, texture = 9 } },
            { label = 'Gafas EMS 20-2', male = { drawable = 20, texture = 2 }, female = { drawable = 20, texture = 2 } },
            { label = 'Gafas EMS 34-0', male = { drawable = 34, texture = 0 }, female = { drawable = 34, texture = 0 } },
            { label = 'Gafas EMS 35-0', male = { drawable = 35, texture = 0 }, female = { drawable = 35, texture = 0 } },
            { label = 'Gafas EMS 37-0', male = { drawable = 37, texture = 0 }, female = { drawable = 37, texture = 0 } }
        },
        hats = {
            { label = 'Gorra Policía 259-0', male = { drawable = 259, texture = 0 }, female = { drawable = 259, texture = 0 } },
            { label = 'Gorra Policía 258-0', male = { drawable = 258, texture = 0 }, female = { drawable = 258, texture = 0 } },
            { label = 'Gorra Policía 256-5', male = { drawable = 256, texture = 5 }, female = { drawable = 256, texture = 5 } },
            { label = 'Gorra Policía 254-5', male = { drawable = 254, texture = 5 }, female = { drawable = 254, texture = 5 } },
            { label = 'Gorra Policía 254-0', male = { drawable = 254, texture = 0 }, female = { drawable = 254, texture = 0 } },
            { label = 'Gorra Policía 251-0', male = { drawable = 251, texture = 0 }, female = { drawable = 251, texture = 0 } },
            { label = 'Gorra Policía 250-0', male = { drawable = 250, texture = 0 }, female = { drawable = 250, texture = 0 } },
            { label = 'Gorra Policía 249-0', male = { drawable = 249, texture = 0 }, female = { drawable = 249, texture = 0 } },
            { label = 'Gorra Policía 235-0', male = { drawable = 235, texture = 0 }, female = { drawable = 235, texture = 0 } },
            { label = 'Gorra Policía 233-0', male = { drawable = 233, texture = 0 }, female = { drawable = 233, texture = 0 } },
            { label = 'Gorra Policía 227-0', male = { drawable = 227, texture = 0 }, female = { drawable = 227, texture = 0 } },
            { label = 'Gorra Policía 46-0', male = { drawable = 46, texture = 0 }, female = { drawable = 46, texture = 0 } },
            { label = 'Casco antidisturbios I', male = { drawable = 126, texture = 0 }, female = { drawable = 125, texture = 0 } },
            { label = 'Casco antidisturbios II', male = { drawable = 124, texture = 0 }, female = { drawable = 123, texture = 0 } }
        },
        watches = {
            { label = 'Reloj EmergencyEUP 1', male = { drawable = 1, texture = 0 }, female = { drawable = 1, texture = 0 } },
            { label = 'Reloj EmergencyEUP 3', male = { drawable = 3, texture = 0 }, female = { drawable = 3, texture = 0 } },
            { label = 'Reloj EmergencyEUP 4', male = { drawable = 4, texture = 0 }, female = { drawable = 4, texture = 0 } },
            { label = 'Reloj EmergencyEUP 6', male = { drawable = 6, texture = 0 }, female = { drawable = 6, texture = 0 } },
            { label = 'Reloj EmergencyEUP 7', male = { drawable = 7, texture = 0 }, female = { drawable = 7, texture = 0 } },
            { label = 'Reloj EmergencyEUP 10', male = { drawable = 10, texture = 0 }, female = { drawable = 10, texture = 0 } },
            { label = 'Reloj EmergencyEUP 11', male = { drawable = 11, texture = 0 }, female = { drawable = 11, texture = 0 } },
            { label = 'Reloj EmergencyEUP 12', male = { drawable = 12, texture = 0 }, female = { drawable = 12, texture = 0 } },
            { label = 'Reloj EmergencyEUP 13', male = { drawable = 13, texture = 0 }, female = { drawable = 13, texture = 0 } },
            { label = 'Reloj EmergencyEUP 14', male = { drawable = 14, texture = 0 }, female = { drawable = 14, texture = 0 } },
            { label = 'Reloj EmergencyEUP 15', male = { drawable = 15, texture = 0 }, female = { drawable = 15, texture = 0 } },
            { label = 'Reloj EmergencyEUP 16', male = { drawable = 16, texture = 0 }, female = { drawable = 16, texture = 0 } },
            { label = 'Reloj EmergencyEUP 18', male = { drawable = 18, texture = 0 }, female = { drawable = 18, texture = 0 } },
            { label = 'Reloj EmergencyEUP 19', male = { drawable = 19, texture = 0 }, female = { drawable = 19, texture = 0 } },
            { label = 'Reloj EmergencyEUP 20', male = { drawable = 20, texture = 0 }, female = { drawable = 20, texture = 0 } },
            { label = 'Reloj EmergencyEUP 30', male = { drawable = 30, texture = 0 }, female = { drawable = 30, texture = 0 } },
            { label = 'Reloj EmergencyEUP 31', male = { drawable = 31, texture = 0 }, female = { drawable = 31, texture = 0 } },
            { label = 'Reloj EmergencyEUP 32', male = { drawable = 32, texture = 0 }, female = { drawable = 32, texture = 0 } },
            { label = 'Reloj EmergencyEUP 33', male = { drawable = 33, texture = 0 }, female = { drawable = 33, texture = 0 } },
            { label = 'Reloj EmergencyEUP 34', male = { drawable = 34, texture = 0 }, female = { drawable = 34, texture = 0 } },
            { label = 'Reloj EmergencyEUP 35', male = { drawable = 35, texture = 0 }, female = { drawable = 35, texture = 0 } },
            { label = 'Reloj EmergencyEUP 36', male = { drawable = 36, texture = 0 }, female = { drawable = 36, texture = 0 } },
            { label = 'Reloj EmergencyEUP 37', male = { drawable = 37, texture = 0 }, female = { drawable = 37, texture = 0 } },
            { label = 'Reloj EmergencyEUP 38', male = { drawable = 38, texture = 0 }, female = { drawable = 38, texture = 0 } },
            { label = 'Reloj EmergencyEUP 39', male = { drawable = 39, texture = 0 }, female = { drawable = 39, texture = 0 } }
        }
    },

    ems = {
        glasses = {
            { label = 'Gafas EMS 63-0', male = { drawable = 63, texture = 0 }, female = { drawable = 63, texture = 0 } },
            { label = 'Gafas EMS 1-1', male = { drawable = 1, texture = 1 }, female = { drawable = 1, texture = 1 } },
            { label = 'Gafas EMS 2-2', male = { drawable = 2, texture = 2 }, female = { drawable = 2, texture = 2 } },
            { label = 'Gafas EMS 3-9', male = { drawable = 3, texture = 9 }, female = { drawable = 3, texture = 9 } },
            { label = 'Gafas EMS 4-6', male = { drawable = 4, texture = 6 }, female = { drawable = 4, texture = 6 } },
            { label = 'Gafas EMS 7-7', male = { drawable = 7, texture = 7 }, female = { drawable = 7, texture = 7 } },
            { label = 'Gafas EMS 9-9', male = { drawable = 9, texture = 9 }, female = { drawable = 9, texture = 9 } },
            { label = 'Gafas EMS 15-7', male = { drawable = 15, texture = 7 }, female = { drawable = 15, texture = 7 } },
            { label = 'Gafas EMS 17-7', male = { drawable = 17, texture = 7 }, female = { drawable = 17, texture = 7 } },
            { label = 'Gafas EMS 17-9', male = { drawable = 17, texture = 9 }, female = { drawable = 17, texture = 9 } },
            { label = 'Gafas EMS 19-9', male = { drawable = 19, texture = 9 }, female = { drawable = 19, texture = 9 } },
            { label = 'Gafas EMS 20-2', male = { drawable = 20, texture = 2 }, female = { drawable = 20, texture = 2 } },
            { label = 'Gafas EMS 34-0', male = { drawable = 34, texture = 0 }, female = { drawable = 34, texture = 0 } },
            { label = 'Gafas EMS 35-0', male = { drawable = 35, texture = 0 }, female = { drawable = 35, texture = 0 } },
            { label = 'Gafas EMS 37-0', male = { drawable = 37, texture = 0 }, female = { drawable = 37, texture = 0 } }
        },
        hats = {
            { label = 'Gorra EMS (LSPD_EUP) - Azul', male = { drawable = 122, texture = 0 }, female = { drawable = 122, texture = 0 } },
            { label = 'Gorra EMS (LSPD_EUP) - Blanca', male = { drawable = 122, texture = 1 }, female = { drawable = 122, texture = 1 } },
            { label = 'Gorra EMS (LSPD_EUP) - Variante 243', male = { drawable = 243, texture = 2 }, female = { drawable = 243, texture = 2 } }
        },
        watches = {
            { label = 'Reloj EmergencyEUP 1', male = { drawable = 1, texture = 0 }, female = { drawable = 1, texture = 0 } },
            { label = 'Reloj EmergencyEUP 3', male = { drawable = 3, texture = 0 }, female = { drawable = 3, texture = 0 } },
            { label = 'Reloj EmergencyEUP 4', male = { drawable = 4, texture = 0 }, female = { drawable = 4, texture = 0 } },
            { label = 'Reloj EmergencyEUP 6', male = { drawable = 6, texture = 0 }, female = { drawable = 6, texture = 0 } },
            { label = 'Reloj EmergencyEUP 7', male = { drawable = 7, texture = 0 }, female = { drawable = 7, texture = 0 } },
            { label = 'Reloj EmergencyEUP 10', male = { drawable = 10, texture = 0 }, female = { drawable = 10, texture = 0 } },
            { label = 'Reloj EmergencyEUP 11', male = { drawable = 11, texture = 0 }, female = { drawable = 11, texture = 0 } },
            { label = 'Reloj EmergencyEUP 12', male = { drawable = 12, texture = 0 }, female = { drawable = 12, texture = 0 } },
            { label = 'Reloj EmergencyEUP 13', male = { drawable = 13, texture = 0 }, female = { drawable = 13, texture = 0 } },
            { label = 'Reloj EmergencyEUP 14', male = { drawable = 14, texture = 0 }, female = { drawable = 14, texture = 0 } },
            { label = 'Reloj EmergencyEUP 15', male = { drawable = 15, texture = 0 }, female = { drawable = 15, texture = 0 } },
            { label = 'Reloj EmergencyEUP 16', male = { drawable = 16, texture = 0 }, female = { drawable = 16, texture = 0 } },
            { label = 'Reloj EmergencyEUP 18', male = { drawable = 18, texture = 0 }, female = { drawable = 18, texture = 0 } },
            { label = 'Reloj EmergencyEUP 19', male = { drawable = 19, texture = 0 }, female = { drawable = 19, texture = 0 } },
            { label = 'Reloj EmergencyEUP 20', male = { drawable = 20, texture = 0 }, female = { drawable = 20, texture = 0 } },
            { label = 'Reloj EmergencyEUP 30', male = { drawable = 30, texture = 0 }, female = { drawable = 30, texture = 0 } },
            { label = 'Reloj EmergencyEUP 31', male = { drawable = 31, texture = 0 }, female = { drawable = 31, texture = 0 } },
            { label = 'Reloj EmergencyEUP 32', male = { drawable = 32, texture = 0 }, female = { drawable = 32, texture = 0 } },
            { label = 'Reloj EmergencyEUP 33', male = { drawable = 33, texture = 0 }, female = { drawable = 33, texture = 0 } },
            { label = 'Reloj EmergencyEUP 34', male = { drawable = 34, texture = 0 }, female = { drawable = 34, texture = 0 } },
            { label = 'Reloj EmergencyEUP 35', male = { drawable = 35, texture = 0 }, female = { drawable = 35, texture = 0 } },
            { label = 'Reloj EmergencyEUP 36', male = { drawable = 36, texture = 0 }, female = { drawable = 36, texture = 0 } },
            { label = 'Reloj EmergencyEUP 37', male = { drawable = 37, texture = 0 }, female = { drawable = 37, texture = 0 } },
            { label = 'Reloj EmergencyEUP 38', male = { drawable = 38, texture = 0 }, female = { drawable = 38, texture = 0 } },
            { label = 'Reloj EmergencyEUP 39', male = { drawable = 39, texture = 0 }, female = { drawable = 39, texture = 0 } }
        }
    },

    fire = {
        glasses = {
             { label = 'Gafas tácticas', male = { drawable = 23, texture = 0 }, female = { drawable = 25, texture = 0 } },
            { label = 'Gafas profesionales oscuras', male = { drawable = 5, texture = 1 }, female = { drawable = 11, texture = 0 } },
            { label = 'Gafas profesionales claras', male = { drawable = 5, texture = 2 }, female = { drawable = 11, texture = 5 } },
            { label = 'Gafas EMS 63-0', male = { drawable = 63, texture = 0 }, female = { drawable = 63, texture = 0 } },
            { label = 'Gafas EMS 1-1', male = { drawable = 1, texture = 1 }, female = { drawable = 1, texture = 1 } },
            { label = 'Gafas EMS 2-2', male = { drawable = 2, texture = 2 }, female = { drawable = 2, texture = 2 } },
            { label = 'Gafas EMS 3-9', male = { drawable = 3, texture = 9 }, female = { drawable = 3, texture = 9 } },
            { label = 'Gafas EMS 4-6', male = { drawable = 4, texture = 6 }, female = { drawable = 4, texture = 6 } },
            { label = 'Gafas EMS 7-7', male = { drawable = 7, texture = 7 }, female = { drawable = 7, texture = 7 } },
            { label = 'Gafas EMS 9-9', male = { drawable = 9, texture = 9 }, female = { drawable = 9, texture = 9 } },
            { label = 'Gafas EMS 15-7', male = { drawable = 15, texture = 7 }, female = { drawable = 15, texture = 7 } },
            { label = 'Gafas EMS 17-7', male = { drawable = 17, texture = 7 }, female = { drawable = 17, texture = 7 } },
            { label = 'Gafas EMS 17-9', male = { drawable = 17, texture = 9 }, female = { drawable = 17, texture = 9 } },
            { label = 'Gafas EMS 19-9', male = { drawable = 19, texture = 9 }, female = { drawable = 19, texture = 9 } },
            { label = 'Gafas EMS 20-2', male = { drawable = 20, texture = 2 }, female = { drawable = 20, texture = 2 } },
            { label = 'Gafas EMS 34-0', male = { drawable = 34, texture = 0 }, female = { drawable = 34, texture = 0 } },
            { label = 'Gafas EMS 35-0', male = { drawable = 35, texture = 0 }, female = { drawable = 35, texture = 0 } },
            { label = 'Gafas EMS 37-0', male = { drawable = 37, texture = 0 }, female = { drawable = 37, texture = 0 } }
        },
        hats = {
            { label = 'Gorra de bombero', male = { drawable = 10, texture = 0 }, female = { drawable = 10, texture = 0 } },
           
        },
        watches = {
            { label = 'Reloj EmergencyEUP 1', male = { drawable = 1, texture = 0 }, female = { drawable = 1, texture = 0 } },
            { label = 'Reloj EmergencyEUP 3', male = { drawable = 3, texture = 0 }, female = { drawable = 3, texture = 0 } },
            { label = 'Reloj EmergencyEUP 4', male = { drawable = 4, texture = 0 }, female = { drawable = 4, texture = 0 } },
            { label = 'Reloj EmergencyEUP 6', male = { drawable = 6, texture = 0 }, female = { drawable = 6, texture = 0 } },
            { label = 'Reloj EmergencyEUP 7', male = { drawable = 7, texture = 0 }, female = { drawable = 7, texture = 0 } },
            { label = 'Reloj EmergencyEUP 10', male = { drawable = 10, texture = 0 }, female = { drawable = 10, texture = 0 } },
            { label = 'Reloj EmergencyEUP 11', male = { drawable = 11, texture = 0 }, female = { drawable = 11, texture = 0 } },
            { label = 'Reloj EmergencyEUP 12', male = { drawable = 12, texture = 0 }, female = { drawable = 12, texture = 0 } },
            { label = 'Reloj EmergencyEUP 13', male = { drawable = 13, texture = 0 }, female = { drawable = 13, texture = 0 } },
            { label = 'Reloj EmergencyEUP 14', male = { drawable = 14, texture = 0 }, female = { drawable = 14, texture = 0 } },
            { label = 'Reloj EmergencyEUP 15', male = { drawable = 15, texture = 0 }, female = { drawable = 15, texture = 0 } },
            { label = 'Reloj EmergencyEUP 16', male = { drawable = 16, texture = 0 }, female = { drawable = 16, texture = 0 } },
            { label = 'Reloj EmergencyEUP 18', male = { drawable = 18, texture = 0 }, female = { drawable = 18, texture = 0 } },
            { label = 'Reloj EmergencyEUP 19', male = { drawable = 19, texture = 0 }, female = { drawable = 19, texture = 0 } },
            { label = 'Reloj EmergencyEUP 20', male = { drawable = 20, texture = 0 }, female = { drawable = 20, texture = 0 } },
            { label = 'Reloj EmergencyEUP 30', male = { drawable = 30, texture = 0 }, female = { drawable = 30, texture = 0 } },
            { label = 'Reloj EmergencyEUP 31', male = { drawable = 31, texture = 0 }, female = { drawable = 31, texture = 0 } },
            { label = 'Reloj EmergencyEUP 32', male = { drawable = 32, texture = 0 }, female = { drawable = 32, texture = 0 } },
            { label = 'Reloj EmergencyEUP 33', male = { drawable = 33, texture = 0 }, female = { drawable = 33, texture = 0 } },
            { label = 'Reloj EmergencyEUP 34', male = { drawable = 34, texture = 0 }, female = { drawable = 34, texture = 0 } },
            { label = 'Reloj EmergencyEUP 35', male = { drawable = 35, texture = 0 }, female = { drawable = 35, texture = 0 } },
            { label = 'Reloj EmergencyEUP 36', male = { drawable = 36, texture = 0 }, female = { drawable = 36, texture = 0 } },
            { label = 'Reloj EmergencyEUP 37', male = { drawable = 37, texture = 0 }, female = { drawable = 37, texture = 0 } },
            { label = 'Reloj EmergencyEUP 38', male = { drawable = 38, texture = 0 }, female = { drawable = 38, texture = 0 } },
            { label = 'Reloj EmergencyEUP 39', male = { drawable = 39, texture = 0 }, female = { drawable = 39, texture = 0 } }
        }
    },

    tow = {
        glasses = {
            { label = 'Gafas profesionales oscuras', male = { drawable = 5, texture = 1 }, female = { drawable = 11, texture = 0 } },
            { label = 'Gafas profesionales claras', male = { drawable = 5, texture = 2 }, female = { drawable = 11, texture = 5 } }
        },
        hats = {},
        watches = {
            { label = 'Reloj EmergencyEUP 1', male = { drawable = 1, texture = 0 }, female = { drawable = 1, texture = 0 } },
            { label = 'Reloj EmergencyEUP 3', male = { drawable = 3, texture = 0 }, female = { drawable = 3, texture = 0 } },
            { label = 'Reloj EmergencyEUP 4', male = { drawable = 4, texture = 0 }, female = { drawable = 4, texture = 0 } },
            { label = 'Reloj EmergencyEUP 6', male = { drawable = 6, texture = 0 }, female = { drawable = 6, texture = 0 } },
            { label = 'Reloj EmergencyEUP 7', male = { drawable = 7, texture = 0 }, female = { drawable = 7, texture = 0 } },
            { label = 'Reloj EmergencyEUP 10', male = { drawable = 10, texture = 0 }, female = { drawable = 10, texture = 0 } },
            { label = 'Reloj EmergencyEUP 11', male = { drawable = 11, texture = 0 }, female = { drawable = 11, texture = 0 } },
            { label = 'Reloj EmergencyEUP 12', male = { drawable = 12, texture = 0 }, female = { drawable = 12, texture = 0 } },
            { label = 'Reloj EmergencyEUP 13', male = { drawable = 13, texture = 0 }, female = { drawable = 13, texture = 0 } },
            { label = 'Reloj EmergencyEUP 14', male = { drawable = 14, texture = 0 }, female = { drawable = 14, texture = 0 } },
            { label = 'Reloj EmergencyEUP 15', male = { drawable = 15, texture = 0 }, female = { drawable = 15, texture = 0 } },
            { label = 'Reloj EmergencyEUP 16', male = { drawable = 16, texture = 0 }, female = { drawable = 16, texture = 0 } },
            { label = 'Reloj EmergencyEUP 18', male = { drawable = 18, texture = 0 }, female = { drawable = 18, texture = 0 } },
            { label = 'Reloj EmergencyEUP 19', male = { drawable = 19, texture = 0 }, female = { drawable = 19, texture = 0 } },
            { label = 'Reloj EmergencyEUP 20', male = { drawable = 20, texture = 0 }, female = { drawable = 20, texture = 0 } },
            { label = 'Reloj EmergencyEUP 30', male = { drawable = 30, texture = 0 }, female = { drawable = 30, texture = 0 } },
            { label = 'Reloj EmergencyEUP 31', male = { drawable = 31, texture = 0 }, female = { drawable = 31, texture = 0 } },
            { label = 'Reloj EmergencyEUP 32', male = { drawable = 32, texture = 0 }, female = { drawable = 32, texture = 0 } },
            { label = 'Reloj EmergencyEUP 33', male = { drawable = 33, texture = 0 }, female = { drawable = 33, texture = 0 } },
            { label = 'Reloj EmergencyEUP 34', male = { drawable = 34, texture = 0 }, female = { drawable = 34, texture = 0 } },
            { label = 'Reloj EmergencyEUP 35', male = { drawable = 35, texture = 0 }, female = { drawable = 35, texture = 0 } },
            { label = 'Reloj EmergencyEUP 36', male = { drawable = 36, texture = 0 }, female = { drawable = 36, texture = 0 } },
            { label = 'Reloj EmergencyEUP 37', male = { drawable = 37, texture = 0 }, female = { drawable = 37, texture = 0 } },
            { label = 'Reloj EmergencyEUP 38', male = { drawable = 38, texture = 0 }, female = { drawable = 38, texture = 0 } },
            { label = 'Reloj EmergencyEUP 39', male = { drawable = 39, texture = 0 }, female = { drawable = 39, texture = 0 } }
        }
    }
}