local o=false local m=1 local p=6 local d=0 local t=0
local modes={{'LSPD_EUP','mp_m_lspd'},{'EmergencyEUP','mp_m_emergency'},{'ROPA BASE / GLOBAL',false}}
local parts={{'Máscara',1},{'Brazos / Torso',3},{'Pantalón',4},{'Bolsas',5},{'Zapatos',6},{'Accesorios',7},{'Camiseta / Interior',8},{'Chaleco / Armor',9},{'Insignias / Decals',10},{'Chaqueta / Top',11}}
local function nd() if modes[m][2] then return GetNumberOfPedCollectionDrawableVariations(PlayerPedId(),parts[p][2],modes[m][2]) else return GetNumberOfPedDrawableVariations(PlayerPedId(),parts[p][2]) end end
local function nt() local n=nd() if n<=0 or d>=n then return 0 end if modes[m][2] then return GetNumberOfPedCollectionTextureVariations(PlayerPedId(),parts[p][2],modes[m][2],d) else return GetNumberOfPedTextureVariations(PlayerPedId(),parts[p][2],d) end end
local function apply() local n=nd() if n<=0 then return end d=(d+n)%n local x=nt() if x>0 then t=(t+x)%x else t=0 end if modes[m][2] then SetPedCollectionComponentVariation(PlayerPedId(),parts[p][2],modes[m][2],d,t,0) else SetPedComponentVariation(PlayerPedId(),parts[p][2],d,t,0) end end
local function tx(x,y,s,v) SetTextFont(0) SetTextScale(s,s) SetTextColour(255,255,255,255) SetTextOutline() SetTextEntry('STRING') AddTextComponentString(v) DrawText(x,y) end
RegisterCommand('ropav3',function() o=not o d=0 t=0 end,false)
CreateThread(function() while true do if not o then Wait(200) else Wait(0) DrawRect(.21,.20,.40,.35,0,0,0,195) tx(.025,.045,.48,'PD5M - Explorador V3') tx(.025,.085,.35,'Origen: '..modes[m][1]) tx(.025,.115,.35,('Pieza: %s [ID %d]'):format(parts[p][1],parts[p][2])) tx(.025,.145,.35,('Drawable: %d / %d'):format(d,math.max(0,nd()-1))) tx(.025,.175,.35,('Texture: %d / %d'):format(t,math.max(0,nt()-1))) tx(.025,.215,.30,'A/D origen | ARR/ABA pieza') tx(.025,.245,.30,'IZQ/DER drawable | Q/E textura') tx(.025,.275,.30,'ENTER imprime en F8 | BACK cerrar')
if IsControlJustPressed(0,34) then m=m-1 if m<1 then m=#modes end d=0 t=0 elseif IsControlJustPressed(0,35) then m=m+1 if m>#modes then m=1 end d=0 t=0 elseif IsControlJustPressed(0,172) then p=p-1 if p<1 then p=#parts end d=0 t=0 elseif IsControlJustPressed(0,173) then p=p+1 if p>#parts then p=1 end d=0 t=0 elseif IsControlJustPressed(0,174) then d=d-1 t=0 apply() elseif IsControlJustPressed(0,175) then d=d+1 t=0 apply() elseif IsControlJustPressed(0,44) then t=t-1 apply() elseif IsControlJustPressed(0,38) then t=t+1 apply() elseif IsControlJustPressed(0,191) then print(('[PD5M V3] %s component=%d drawable=%d texture=%d'):format(modes[m][1],parts[p][2],d,t)) elseif IsControlJustPressed(0,177) then o=false end end end end)
